FROM ros:noetic-perception-focal

# arm64/Jetson variant of Dockerfile_ros1_20_04.
# osrf/ros:noetic-desktop-full is amd64-only, so this uses the official
# multi-arch ros:noetic-perception-focal image instead (has cv_bridge,
# image_transport, etc. which kalibr needs; skips gazebo/rviz which it doesn't).

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
        git wget autoconf automake nano \
        python3-dev python3-pip python3-scipy python3-matplotlib \
        ipython3 python3-wxgtk4.0 python3-tk python3-igraph python3-pyx \
        libeigen3-dev libboost-all-dev libsuitesparse-dev \
        doxygen \
        libopencv-dev \
        libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
        python3-catkin-tools python3-osrf-pycommon


# Create the workspace and build kalibr in it
ENV WORKSPACE /catkin_ws

RUN mkdir -p $WORKSPACE/src && \
        cd $WORKSPACE && \
        catkin init && \
        catkin config --extend /opt/ros/noetic && \
        catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

ADD . $WORKSPACE/src/kalibr

RUN     cd $WORKSPACE &&\
        catkin build -j2 -p1

# Allow using the manual focal length if auto-init fails
# https://github.com/ethz-asl/kalibr/pull/346
ENTRYPOINT export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1 && \
        cd $WORKSPACE && \
        /bin/bash
